### ISSUE TITLE
error while installing SimpleElastix via SuperBuild

### ISSUE THREAD

**Issue by LiesVan** [SuperElastix/SimpleElastix#143]
Hi

I get an error while installing SimpleElastix via the SuperBuild. The error is: 'sitkExplicitITK.h' file not found #include "sitkExplicitITK.h". 

I just followed the steps described in the 'Getting Started' doc of SimpleElastix (SuperBuild on Linux) (http://simpleelastix.readthedocs.io/GettingStarted.html#superbuild-on-mac-os-x). Everything works until I get the error during the '$ make' step. 

For completeness, some things I have done and some properties of the pc:
 1) I changed the '$ make - j4' step into '$ make' because I only have 8GB of RAM.
 2) I changed the language I want to link with SimpleElastix in cmake because I only want to use SimpleElastix via python and not via the other possible languages (e.g. tcl).
3) My python version is Python 2.7 and I use it via Anaconda.
4) I work on a macOS Sierra, version 10.12.6.

Does anyone have an idea what the problem is?

**Comment by kaspermarstal** [comment]
Hi @LiesVan, I don't know what the problem is but if you use master you could try the develop branch which has seen a lot of work since the last release.

**Comment by LiesVan** [comment]
I just tried to install the develop branch, but it gave the same error :/

**Comment by kaspermarstal** [comment]
I don't know why you are experiencing this issue. Maybe something went wrong during CMake configuration. Try to delete the entire build folder and start from scratch.

You could also try to compile SimpleITK to see if you hit the same error there. At least we will know if something is wrong with SimpleElastix then.

**Comment by LiesVan** [comment]
I deleted the build folder and started the installation again. This gave a different error than before:
Undefined symbols for architecture x86_64:
  "_Tcl_MainEx", referenced from:
      _main in SimpleITKTCL_wrap.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [Wrapping/Tcl/bin/SimpleITKTclsh] Error 1
make[4]: *** [Wrapping/Tcl/CMakeFiles/SimpleITKTclsh.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2

and installation of SimpleITK gave no problems.

**Comment by kaspermarstal** [comment]
Try to run it with `-j1`. Does it say which symbols are missing?

**Comment by LiesVan** [comment]
Running with -j1 gives the same error, but maybe this helps: when I execute '$ ld' in the terminal, I get the following output:

-vld: warning: -arch not specified
ld: warning: -macosx_version_min not specified, assuming 10.10
ld: no object files specified for inferred architecture x86_64​

I found that people with similar problems were able to resolve them by executing '$ make clean_all && make -j4', do you think this could help? I will try as soon as possible.

[(https://github.com/dmlc/xgboost/issues/1839)]

**Comment by kaspermarstal** [comment]
Yes I think it is worth a try. But delete the entire directory and start over (not just `make clean`).

**Comment by kaspermarstal** [comment]
Closing due to inactivity. Feel free to reopen if this is still an issue.
